security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    hide_user_not_found: false

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    access_denied_url: /unauthorized

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: /{_locale}/app_rooms
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%kernel.secret%'


    access_control:
    - { path: "^/{_locale}/login", roles: PUBLIC_ACCESS }
    - { path: "^/{_locale}/unauthorized", roles: PUBLIC_ACCESS }
    - { path: "^/{_locale}/error", roles: PUBLIC_ACCESS }

    # Règles spécifiques
    - { path: "^/{_locale}/rooms/[a-zA-Z0-9]+/(update|delete)$", roles: ROLE_MANAGER }
    - { path: "^/{_locale}/as", roles: ROLE_TECHNICIAN }
    - { path: "^/{_locale}/todolist", roles: ROLE_TECHNICIAN }

    # Règles générales
    - { path: "^/{_locale}/rooms$", roles: PUBLIC_ACCESS }
    - { path: "^/{_locale}/rooms/[a-zA-Z0-9]+$", roles: PUBLIC_ACCESS }

    # Par défaut, toutes les autres routes sont publiques
    - { path: "^/{_locale}/", roles: PUBLIC_ACCESS }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
