security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    hide_user_not_found: false

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    access_denied_url: /unauthorized

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_rooms
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%kernel.secret%'


    access_control:
        # Permet l'accès à /login à tout le monde, même sans authentification
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # Permet l'accès à /rooms à tout le monde, même sans authentification
        - { path: ^/rooms, roles: PUBLIC_ACCESS }

        # Permet l'accès à /unauthorized et /error à tout le monde
        - { path: ^/error, roles: PUBLIC_ACCESS }

        # Permet l'accès à /as uniquement aux managers
        - { path: ^/as, roles: ROLE_TECHNICIAN }

        - { path: ^/todolist, roles: ROLE_TECHNICIAN }

        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
