security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    hide_user_not_found: false

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    access_denied_url: /unauthorized

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: /{_locale}/app_rooms
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%kernel.secret%'


    access_control:
        # Permet l'accès à /{_locale}/login à tout le monde
        - { path: "^/{_locale}/login", roles: PUBLIC_ACCESS }

        # Permet l'accès à /{_locale}/unauthorized et /{_locale}/error à tout le monde
        - { path: "^/{_locale}/unauthorized", roles: PUBLIC_ACCESS }
        - { path: "^/{_locale}/error", roles: PUBLIC_ACCESS }

        # Permet l'accès à la liste générale des salles pour tout le monde
        - { path: "^/{_locale}/rooms$", roles: PUBLIC_ACCESS }

        # Permet à tout le monde d'accéder aux détails d'une salle
        - { path: "^/{_locale}/rooms/[a-zA-Z0-9]+$", roles: PUBLIC_ACCESS }

        # Restreint l'accès aux routes update ou delete des salles aux managers uniquement
        - { path: "^/{_locale}/rooms/[a-zA-Z0-9]+/(update|delete)$", roles: ROLE_MANAGER }

        # Permet l'accès à /{_locale}/as uniquement aux techniciens
        - { path: "^/{_locale}/as", roles: ROLE_TECHNICIAN }

        # Permet l'accès à /{_locale}/todolist uniquement aux techniciens
        - { path: "^/{_locale}/todolist", roles: ROLE_TECHNICIAN }

        # Par défaut, toutes les autres routes sont publiques
        - { path: "^/{_locale}/", roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
