security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    hide_user_not_found: false

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    access_denied_url: /unauthorized

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: /rooms
                csrf_token_manager: security.csrf.token_manager
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%kernel.secret%'

    access_control:
        # Public Routes
        - { path: "^/$", roles: PUBLIC_ACCESS }
        - { path: "^/[a-z]{2}$", roles: PUBLIC_ACCESS }
        - { path: "^/[a-z]{2}/login$", roles: PUBLIC_ACCESS }
        - { path: "^/[a-z]{2}/unauthorized$", roles: PUBLIC_ACCESS }
        - { path: "^/[a-z]{2}/error$", roles: PUBLIC_ACCESS }
        - { path: "^/[a-z]{2}/rooms$", roles: PUBLIC_ACCESS }
        - { path: "^/[a-z]{2}/rooms/[a-zA-Z0-9]+$", roles: PUBLIC_ACCESS }

        # Protected Routes
        - { path: "^/[a-z]{2}/rooms/[a-zA-Z0-9]+/update$", roles: ROLE_MANAGER }
        - { path: "^/[a-z]{2}/rooms/[a-zA-Z0-9]+/delete$", roles: ROLE_MANAGER }
        - { path: "^/[a-z]{2}/rooms/add", roles: ROLE_MANAGER }
        - { path: "^/[a-z]{2}/as", roles: ROLE_TECHNICIAN }
        - { path: "^/[a-z]{2}/todolist", roles: ROLE_TECHNICIAN }
        - { path: "^/[a-z]{2}/home", roles: IS_AUTHENTICATED_FULLY }
        - { path: "^/[a-z]{2}/rooms/[a-zA-Z0-9]+/analytics/[a-zA-Z0-9]+$", roles: ROLE_MANAGER }


        # Default: All other routes require at least ROLE_USER
        # - { path: "^/[a-z]{2}/", roles: IS_AUTHENTICATED_FULLY }



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
