controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app:
    resource: '../src/Controller/'
    type: annotation
    prefix: '/{_locale}'
    requirements:
        _locale: 'en|fr'

app_home:
    path: '/{_locale}/'
    controller: App\Controller\HomeController::index
    requirements:
        _locale: 'en|fr'