controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app:
    resource: '../src/Controller/'
    type: annotation
    prefix: '/{_locale}'
    requirements:
        _locale: 'en|fr'

app_rooms:
    path: '/{_locale}/rooms'
    controller: App\Controller\RoomController::index
    requirements:
        _locale: 'en|fr'

redirect_root_to_locale_rooms:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_rooms
        permanent: false
        _locale: 'fr'

redirect_locale_to_rooms:
    path: '/{_locale}'
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_rooms
        permanent: false
    requirements:
        _locale: 'en|fr'