#routes.yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app:
    resource: '../src/Controller/'
    type: annotation
    prefix: '/{_locale}'
    requirements:
        _locale: 'en|fr'

app_rooms:
    path: '/{_locale}/rooms'
    controller: App\Controller\RoomController::index
    requirements:
        _locale: 'en|fr'

app_rooms_details:
    path: '/{_locale}/rooms/{name}'
    controller: App\Controller\RoomController::details
    requirements:
        _locale: 'en|fr'

root_redirect:
    path: '/'
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_rooms
        permanent: false
        _locale: 'en'

rooms_redirect:
    path: '/{_locale}/rooms'
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_rooms
        permanent: false
        _locale: 'en|fr'

rooms_details_redirect:
    path: '/{_locale}/rooms/{name}'
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_rooms_details
        permanent: false
        _locale: 'en|fr'

app_logout:
    path: '/{_locale}/logout'
    controller: Symfony\Bundle\SecurityBundle\Controller\LogoutController
    requirements:
        _locale: 'en|fr'


app_unauthorized_no_locale:
    path: /unauthorized
    controller: App\Controller\SecurityController::unauthorized



